--1. Tạo view có hiển thị như sau:
--select * from aggredates;

CREATE VIEW VIEW_AGGREGATES
AS
SELECT *
FROM AGGREDATES;

--2. Tạo view để nhập số liệu vào bảng ASIGNMENT với các điều kiện sau:
-- PROJID <2000, P_START_DATE<P_END_DATE
-- Các giá trị có thể chấp nhận của assign_type là PS, WT hoặc ED
-- EMPNO có giá trị NOT NULL
-- BILL_RATE < 50 Với ASSIGN_TYPE Là PS
-- BILL_RATE < 60 Với ASSIGN_TYPE Là WT
-- BILL_RATE < 70 Với ASSIGN_TYPE Là ED

CREATE VIEW VIEW_ASSIGNMENT_PHUONGTD
AS
SELECT *
FROM ASSIGNMENTS_PHUONGTD
WHERE PROJID < 2000
  AND A_START_DATE < A_END_DATE
  AND (ASSIGN_TYPE = 'PS' OR ASSIGN_TYPE = 'WT' OR ASSIGN_TYPE = 'ED')
  AND EMPNO IS NOT NULL
  AND ((BILL_AMOUNT < 50 AND ASSIGN_TYPE = 'PS') OR
       (BILL_AMOUNT < 60 AND ASSIGN_TYPE = 'WT') OR
       (BILL_AMOUNT < 70 AND ASSIGN_TYPE = 'ED'))
WITH CHECK OPTION CONSTRAINT ASSIGNMENTS_PHUONGTD_CHECK

--3. Định nghĩa bảng MESSAGES có cấu trúc
CREATE TABLE MESSAGES_PHUONGTD
(
    NUMCOL1  NUMBER(9, 2),
    NUMCOL2  NUMBER(9, 2),
    CHARCOL1 VARCHAR2(60),
    CHARCOL2 VARCHAR2(60),
    DATECOL1 DATE,
    DATECOL2 DATE
)

CREATE VIEW VIEW_MESSAGES_PHUONGTD
ASD
SELECT *
FROM MESSAGES_PHUONGTD

