--1
SELECT DISTINCT *
FROM SALGRADE;

--2
SELECT DISTINCT *
FROM EMP;

--3
SELECT DISTINCT *
FROM EMP
WHERE JOB = 'ANALYST'
   OR JOB = 'CLERK'
   OR JOB = 'MANAGER'
   OR JOB = 'PRESIDENT'
   OR JOB = 'SALESMAN';

--4
SELECT DISTINCT ENAME, (SAL * 12) as REMUNERATION
FROM EMP
WHERE SAL IS NOT NULL;

--5
SELECT DISTINCT ENAME
                    || ' HAS HELP THE POSITION OF ' || JOB
                    || ' IN DEPT ' || DEPTNO
                    || ' SINCE ' || TO_CHAR(HIREDATE, 'dd-MM-yyyy')
FROM EMP;


--6
DESCRIBE EMP;

--7
SELECT DISTINCT TO_CHAR(SAL, 'fm999G999G990')   as SALARY,
                TO_CHAR(HIREDATE, 'dd-MM-yyyy') as DATE_
FROM EMP
