--1
SELECT DISTINCT *
FROM SALGRADE;

--2
SELECT DISTINCT *
FROM EMP;

--3
SELECT DISTINCT *
FROM EMP
WHERE JOB = 'ANALYST'
   OR JOB = 'CLERK'
   OR JOB = 'MANAGER'
   OR JOB = 'PRESIDENT'
   OR JOB = 'SALESMAN';

--4
SELECT DISTINCT ENAME, (SAL * 12) as REMUNERATION
FROM EMP
WHERE SAL IS NOT NULL;

--5
SELECT DISTINCT ENAME
                    || ' HAS HELP THE POSITION OF ' || JOB
                    || ' IN DEPT ' || DEPTNO
                    || ' SINCE ' || HIREDATE
FROM EMP;


--6
DESCRIBE EMP;

--7
SELECT DISTINCT TO_CHAR(SAL, 'fm999G999G990')   as SALARY,
                TO_CHAR(HIREDATE, 'dd-MM-yyyy') as DATE_
FROM EMP

-----------------3-----------------
--1
SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000

--2
SELECT DEPTNO, DNAME
FROM DEPT
ORDER BY DNAME

--3
SELECT *
FROM EMP
WHERE DEPTNO = 10
   OR DEPTNO = 20

--4
SELECT ENAME, JOB
FROM EMP
WHERE JOB = 'CLERK'
  AND DEPTNO = 20

--5
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%TH%'
   OR ENAME LIKE '%LL%'

--6
SELECT DISTINCT ENAME, JOB, SAL
FROM EMP
WHERE JOB NOT LIKE 'PRESIDENT'

--7
SELECT ENAME, DEPTNO, HIREDATE
FROM EMP
WHERE TO_CHAR(HIREDATE, 'yyyy') = 1983

--8
SELECT ENAME, (SAL * 12) AS ANUAL_SAL, COMM
FROM EMP
WHERE JOB = 'SALESMAN'
  AND SAL > COMM
ORDER BY SAL DESC, ENAME
