--1. Thêm dữ liệu vào bảng PROJECTS.
INSERT INTO PROJECT_PHUONGTD(PROJID, P_DESC, P_START_DATE, P_END_DATE, BUDGET_AMOUNT, MAX_NO_STAFF, COMMENTS)
VALUES (1, 'WRITE C030 COURSE', '02-JAN-88 ', '07-JAN-88 ', 500, 1, 'COMMENTS')

INSERT INTO PROJECT_PHUONGTD(PROJID, P_DESC, P_START_DATE, P_END_DATE, BUDGET_AMOUNT, MAX_NO_STAFF, COMMENTS)
VALUES (2, 'PROOF READ NOTES', '01-JAN-89', '10-JAN-89', 600, 1, 'COMMENTS 2')

--2. Thêm dữ liệu vào bảng ASSIGNMENTS.
INSERT INTO ASSIGNMENTS_PHUONGTD(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (1, 7369, '01-JAN-88', '03-JAN-88', 50.00, 'WR', 15);

INSERT INTO ASSIGNMENTS_PHUONGTD(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (1, 7902, '04-JAN-88', '07-JAN-88', 55.00, 'WR', 20);

INSERT INTO ASSIGNMENTS_PHUONGTD(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (2, 7844, '01-JAN-89', ' 10-JAN-89 ', 45.50, 'PF', 30);

--3. Cập nhật trường ASIGNMENT_TYPE từ WT thành WR.
UPDATE ASSIGNMENTS_PHUONGTD
SET ASSIGN_TYPE = 'WT'
WHERE ASSIGN_TYPE = 'WR'

--4. Nhập thêm số liệu vào bảng ASSIGNMENTS.
INSERT INTO ASSIGNMENTS_PHUONGTD(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (2, 7369, '01-JAN-88', '03-JAN-88', 50.00, 'WR', 15);

INSERT INTO ASSIGNMENTS_PHUONGTD(PROJID, EMPNO, A_START_DATE, A_END_DATE, BILL_AMOUNT, ASSIGN_TYPE, HOURS)
VALUES (2, 7902, '04-JAN-88', '07-JAN-88', 55.00, 'WR', 20);
